# Generated by Django 3.2 on 2021-10-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='failure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('failure_system_name', models.CharField(default=None, max_length=255, verbose_name='所属系统')),
                ('failure_happen_time', models.DateTimeField(verbose_name='开始时间')),
                ('failure_recover_time', models.DateTimeField(verbose_name='结束时间')),
                ('keep_time', models.CharField(default=None, max_length=255, verbose_name='持续时间')),
                ('failure_scope_batch_id', models.CharField(default=None, max_length=255, verbose_name='影响范围')),
                ('failure_impact', models.TextField(default=None, max_length=255, verbose_name='故障现象')),
                ('failure_level', models.CharField(default=None, max_length=255, verbose_name='故障等级')),
                ('measure_completion_status', models.CharField(default=None, max_length=255, verbose_name='整改进度')),
                ('affected_customer', models.CharField(max_length=255, verbose_name='影响人数')),
                ('affected_orders', models.CharField(max_length=255, verbose_name='影响单量')),
                ('affected_amount', models.CharField(max_length=255, verbose_name='影响金额')),
                ('state', models.IntegerField(default=0, verbose_name='填写状态')),
            ],
        ),
    ]
